name: narracity
description: "A Narracity is an app that enhances outdoor activiites. It leads you through a city with the narrator who tells you about history and culture of the place or run a role-playing game. "
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  flutter_bloc: ^9.1.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/cat.webp